language: ruby

rvm: '2.6.3'

services:
  - postgresql

before_script:
  - bundle install
  - bundle exec rake db:create db:schema:load
  - RACK_ENV=test bundle exec rake db:seed

script:
- mkdir -p spec && bundle exec rspec spec
