rvm: '2.6.3'

script:
  - mkdir -p spec && bundle exec rspec spec


services:
  - postgresql

before_script:
  - bundle install
  - bundle exec rake db:create db:schema:load
  - RACK_ENV=test bundle exec db:seed
