default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost


production:
  <<: *default
  database: makersbnb

development:
  <<: *default
  database: makersbnb_dev

test: &test
  <<: *default
  database: makersbnb_test
