# This defines the connection to the database based on the RACK_ENV.
# If RACK_ENV isn't set, the default is development.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

production:
  <<: *default
  database: makersbnb

development:
  <<: *default
  database: makersbnb_dev

test: &test
  <<: *default
  database: makersbnb_test
